//! Bounded authored font sources, without resource resolution or support selection.

use crate::{
    CssFontFaceSource, CssFontFaceSourceList, CssFontFaceUrlSource, CssFontFormat,
    CssFontFormatHint, CssFontLocalName, CssFontTechHint, CssSpecifiedValueSerializationError,
    CssSpecifiedValueSerializationLimits, specified_rule_serialization::SpecifiedRuleWriter,
};

type Result<T> = std::result::Result<T, CssSpecifiedValueSerializationError>;

fn charge(writer: &mut SpecifiedRuleWriter, nodes: usize) -> Result<()> {
    writer.context.charge_input(nodes)?;
    writer.context.charge_projection(nodes)
}

impl CssFontLocalName {
    /// Emits `local()` containing the CSSOM string serialization of the decoded name.
    /// Identifier-derived names are quoted too; stored name text remains unchanged.
    pub fn serialize_specified(&self) -> Result<String> {
        self.serialize_specified_with_limits(CssSpecifiedValueSerializationLimits::default())
    }

    /// Charges the local wrapper and string target under one cumulative budget.
    /// Failure returns no partial text and does not select or load a local font.
    pub fn serialize_specified_with_limits(
        &self,
        limits: CssSpecifiedValueSerializationLimits,
    ) -> Result<String> {
        let mut writer = crate::specified_rule_serialization::SpecifiedRuleWriter::new(limits);
        self.append_to_rule_writer(&mut writer)?;
        Ok(writer.css)
    }

    pub(crate) fn append_to_rule_writer(
        &self,
        writer: &mut crate::specified_rule_serialization::SpecifiedRuleWriter,
    ) -> std::result::Result<(), crate::CssSpecifiedValueSerializationError> {
        self.append_specified(writer)?;
        Ok(())
    }

    pub(crate) fn append_specified(&self, writer: &mut SpecifiedRuleWriter) -> Result<()> {
        charge(writer, 2)?;
        writer.append("local(")?;
        writer.append_string(self.as_str())?;
        writer.append(")")
    }
}

impl CssFontFaceUrlSource {
    /// Emits the authored URL followed by its optional format and ordered technologies.
    /// Keyword and string format productions remain distinct, including empty strings.
    pub fn serialize_specified(&self) -> Result<String> {
        self.serialize_specified_with_limits(CssSpecifiedValueSerializationLimits::default())
    }

    /// Shares URL visits, hint visits, escaping and generated bytes in one budget.
    /// One source node, one format argument when present, and one technology-list
    /// node plus each technology supplement the URL provider's documented visits.
    /// Failure returns no partial text; resource queries and stored values are unchanged.
    pub fn serialize_specified_with_limits(
        &self,
        limits: CssSpecifiedValueSerializationLimits,
    ) -> Result<String> {
        let mut writer = crate::specified_rule_serialization::SpecifiedRuleWriter::new(limits);
        self.append_to_rule_writer(&mut writer)?;
        Ok(writer.css)
    }

    pub(crate) fn append_to_rule_writer(
        &self,
        writer: &mut crate::specified_rule_serialization::SpecifiedRuleWriter,
    ) -> std::result::Result<(), crate::CssSpecifiedValueSerializationError> {
        self.append_specified(writer)?;
        Ok(())
    }

    pub(crate) fn append_specified(&self, writer: &mut SpecifiedRuleWriter) -> Result<()> {
        charge(writer, 1)?;
        self.url().append_specified(writer)?;
        if let Some(format) = self.format() {
            charge(writer, 1)?;
            writer.append(" format(")?;
            match format {
                CssFontFormat::Keyword(value) => writer.append(format_keyword(*value))?,
                CssFontFormat::String(value) => writer.append_string(value.as_str())?,
            }
            writer.append(")")?;
        }
        if !self.tech().is_empty() {
            charge(writer, 1)?;
            writer.append(" tech(")?;
            for (index, tech) in self.tech().iter().enumerate() {
                charge(writer, 1)?;
                if index != 0 {
                    writer.append(", ")?;
                }
                writer.append(tech_keyword(*tech))?;
            }
            writer.append(")")?;
        }
        Ok(())
    }
}

impl CssFontFaceSource {
    /// Emits one retained local or URL source through its concrete provider.
    pub fn serialize_specified(&self) -> Result<String> {
        self.serialize_specified_with_limits(CssSpecifiedValueSerializationLimits::default())
    }

    /// Delegates the complete cumulative budget without adding an enum-dispatch visit.
    pub fn serialize_specified_with_limits(
        &self,
        limits: CssSpecifiedValueSerializationLimits,
    ) -> Result<String> {
        let mut writer = crate::specified_rule_serialization::SpecifiedRuleWriter::new(limits);
        self.append_to_rule_writer(&mut writer)?;
        Ok(writer.css)
    }

    pub(crate) fn append_to_rule_writer(
        &self,
        writer: &mut crate::specified_rule_serialization::SpecifiedRuleWriter,
    ) -> std::result::Result<(), crate::CssSpecifiedValueSerializationError> {
        self.append_specified(writer)?;
        Ok(())
    }

    pub(crate) fn append_specified(&self, writer: &mut SpecifiedRuleWriter) -> Result<()> {
        match self {
            Self::Local(value) => value.append_specified(writer),
            Self::Url(value) => value.append_specified(writer),
        }
    }
}

impl CssFontFaceSourceList {
    /// Emits the checked nonempty source list in retained order, separated by `, `.
    pub fn serialize_specified(&self) -> Result<String> {
        self.serialize_specified_with_limits(CssSpecifiedValueSerializationLimits::default())
    }

    /// Charges one list node and every source provider under the same budget.
    /// Failure is atomic; duplicate technologies and prioritized sources are retained.
    pub fn serialize_specified_with_limits(
        &self,
        limits: CssSpecifiedValueSerializationLimits,
    ) -> Result<String> {
        let mut writer = crate::specified_rule_serialization::SpecifiedRuleWriter::new(limits);
        self.append_to_rule_writer(&mut writer)?;
        Ok(writer.css)
    }

    pub(crate) fn append_to_rule_writer(
        &self,
        writer: &mut crate::specified_rule_serialization::SpecifiedRuleWriter,
    ) -> std::result::Result<(), crate::CssSpecifiedValueSerializationError> {
        self.append_specified(writer)?;
        Ok(())
    }

    pub(crate) fn append_specified(&self, writer: &mut SpecifiedRuleWriter) -> Result<()> {
        charge(writer, 1)?;
        for (index, source) in self.sources().iter().enumerate() {
            if index != 0 {
                writer.append(", ")?;
            }
            source.append_specified(writer)?;
        }
        Ok(())
    }
}

fn format_keyword(value: CssFontFormatHint) -> &'static str {
    match value {
        CssFontFormatHint::Woff => "woff",
        CssFontFormatHint::Woff2 => "woff2",
        CssFontFormatHint::TrueType => "truetype",
        CssFontFormatHint::OpenType => "opentype",
        CssFontFormatHint::Collection => "collection",
        CssFontFormatHint::EmbeddedOpenType => "embedded-opentype",
        CssFontFormatHint::Svg => "svg",
    }
}

fn tech_keyword(value: CssFontTechHint) -> &'static str {
    match value {
        CssFontTechHint::Variations => "variations",
        CssFontTechHint::Palettes => "palettes",
        CssFontTechHint::ColorCOLRv0 => "color-colrv0",
        CssFontTechHint::ColorCOLRv1 => "color-colrv1",
        CssFontTechHint::ColorSVG => "color-svg",
        CssFontTechHint::ColorSbix => "color-sbix",
        CssFontTechHint::ColorCBDT => "color-cbdt",
        CssFontTechHint::FeaturesOpenType => "features-opentype",
        CssFontTechHint::FeaturesAAT => "features-aat",
        CssFontTechHint::FeaturesGraphite => "features-graphite",
        CssFontTechHint::Incremental => "incremental",
    }
}
