//! Immutable ordered contributions and shared authored rule/selector contexts.

use std::fmt;
use std::sync::Arc;

use crate::syntax::*;
use crate::{
    CssCustomMediaRule, CssExpansion, CssExpansionError, CssFontFeatureValuesRule, CssParseReport,
    CssRecoveryDiagnostic, CssSourcePosition, expand_declaration,
};

/// Traversal and output budgets for one atomic stylesheet normalization.
///
/// Top-level rules have depth zero. Every visited rule, including an implicit
/// nested-declaration run, counts once. Emitted declaration occurrences count
/// once each; their longhand members count individually, while a custom,
/// universal-reset, or pending expansion counts as one member. Declarations
/// inside retained font, page, and keyframe payloads are not individually emitted.
/// These budgets do not bound payload bytes, allocator usage, or process memory.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CssNormalizationLimits {
    max_rule_depth: u32,
    max_rules: usize,
    max_declarations: usize,
    max_contributions: usize,
}

impl CssNormalizationLimits {
    /// Sets budgets without raising the shared 256-level structural ceiling.
    /// Zero counts admit only output that consumes no units of that resource.
    #[must_use]
    pub const fn try_new(
        max_rule_depth: u32,
        max_rules: usize,
        max_declarations: usize,
        max_contributions: usize,
    ) -> Option<Self> {
        if max_rule_depth > crate::STRUCTURAL_NESTING_LIMIT {
            None
        } else {
            Some(Self {
                max_rule_depth,
                max_rules,
                max_declarations,
                max_contributions,
            })
        }
    }

    /// Returns the maximum number of enclosing rule occurrences.
    #[must_use]
    pub const fn max_rule_depth(self) -> u32 {
        self.max_rule_depth
    }

    /// Returns the maximum visited rule count.
    #[must_use]
    pub const fn max_rules(self) -> usize {
        self.max_rules
    }

    /// Returns the maximum emitted declaration-occurrence count.
    #[must_use]
    pub const fn max_declarations(self) -> usize {
        self.max_declarations
    }

    /// Returns the maximum emitted contribution-member count.
    #[must_use]
    pub const fn max_contributions(self) -> usize {
        self.max_contributions
    }
}

impl Default for CssNormalizationLimits {
    /// Retains the structural ceiling and imposes no additional count policy.
    fn default() -> Self {
        Self {
            max_rule_depth: crate::STRUCTURAL_NESTING_LIMIT,
            max_rules: usize::MAX,
            max_declarations: usize::MAX,
            max_contributions: usize::MAX,
        }
    }
}

/// The exact traversal or output resource whose normalization budget was exceeded.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CssNormalizationResource {
    RuleDepth,
    Rules,
    Declarations,
    Contributions,
}

/// An atomic normalization failure, distinct from parser recovery diagnostics.
#[non_exhaustive]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CssNormalizationErrorKind {
    /// An emitted declaration requires intrinsic expansion that is not implemented.
    UnsupportedDeclaration(CssExpansionError),
    /// A traversal/output budget failed before admitting the responsible unit.
    LimitExceeded {
        resource: CssNormalizationResource,
        limit: usize,
    },
}

/// A typed failure retaining the responsible source occurrence and context.
///
/// Failure exposes no partially normalized sheet and never mutates authored
/// syntax. Positions are optional provenance; absent coordinates are not
/// replaced with generated byte offsets. Rule-admission failures identify their
/// containing context, while declaration failures identify their owning rule.
#[derive(Clone, Debug)]
pub struct CssNormalizationError {
    failure: Box<NormalizationFailure>,
}

#[derive(Clone, Debug)]
struct NormalizationFailure {
    kind: CssNormalizationErrorKind,
    position: Option<CssSourcePosition>,
    rule_context: Option<CssRuleContext>,
    declaration: Option<CssDeclaration>,
    declaration_order: Option<usize>,
}

impl CssNormalizationError {
    /// Returns the typed capability or resource failure.
    #[must_use]
    pub fn kind(&self) -> &CssNormalizationErrorKind {
        &self.failure.kind
    }

    /// Returns the responsible authored position, when one exists.
    #[must_use]
    pub fn position(&self) -> Option<CssSourcePosition> {
        self.failure.position
    }

    /// Returns the responsible declaration occurrence, when admitting a declaration failed.
    #[must_use]
    pub fn declaration(&self) -> Option<&CssDeclaration> {
        self.failure.declaration.as_ref()
    }

    /// Returns its zero-based emitted-declaration ordinal, including the failed occurrence.
    #[must_use]
    pub fn declaration_order(&self) -> Option<usize> {
        self.failure.declaration_order
    }

    /// Returns the owning rule for a declaration failure, or enclosing rule for rule admission.
    #[must_use]
    pub fn rule_context(&self) -> Option<&CssRuleContext> {
        self.failure.rule_context.as_ref()
    }

    fn new(
        kind: CssNormalizationErrorKind,
        position: Option<CssSourcePosition>,
        rule_context: Option<&CssRuleContext>,
        declaration: Option<(&CssDeclaration, usize)>,
    ) -> Self {
        Self {
            failure: Box::new(NormalizationFailure {
                kind,
                position,
                rule_context: rule_context.cloned(),
                declaration: declaration.map(|(source, _)| source.clone()),
                declaration_order: declaration.map(|(_, order)| order),
            }),
        }
    }
}

impl fmt::Display for CssNormalizationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.kind() {
            CssNormalizationErrorKind::UnsupportedDeclaration(error) => {
                write!(formatter, "stylesheet normalization failed: {error}")
            }
            CssNormalizationErrorKind::LimitExceeded { resource, limit } => {
                write!(
                    formatter,
                    "stylesheet normalization exceeded {resource:?} budget {limit}"
                )
            }
        }
    }
}

impl std::error::Error for CssNormalizationError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self.kind() {
            CssNormalizationErrorKind::UnsupportedDeclaration(error) => Some(error),
            CssNormalizationErrorKind::LimitExceeded { .. } => None,
        }
    }
}

/// How an authored selector binds to its shared enclosing selector or scope context.
///
/// A nested parent binding represents the complete parent list: each `&` uses
/// that list's maximum specificity, including implied anchors. Without a parent
/// list, explicit `&` anchors match the context's scope elements and contribute
/// zero specificity. The enum does not calculate specificity or match anything.
/// Scope anchors remain distinct from authored nesting anchors. Selector-function
/// structure is retained, so downstream specificity rules such as `:where()`
/// remain applicable.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CssSelectorBinding {
    /// An ordinary or scoped selector with no implied parent anchor.
    Absolute,
    /// A nested selector with no explicit anchor or leading combinator.
    ImplicitDescendant,
    /// An authored leading combinator binds to the parent list, or nearest scope
    /// when the selector belongs directly to a scoped style rule.
    LeadingCombinator(CssSelectorCombinator),
    /// One or more authored nesting anchors use the enclosing selector context.
    /// With [`CssSelectorContext::parent`] present, they bind to that complete list
    /// and use its maximum specificity. Without a parent, they match the context's
    /// scope elements and contribute zero specificity. Containing selector functions
    /// retain their own specificity rules.
    ExplicitAnchors,
    /// The scoped-selector grammar supplied an authored scope anchor.
    ScopeAnchors,
}

/// An intact authored selector plus its intrinsic enclosing-context binding.
#[derive(Clone, Debug)]
pub struct CssNormalizedSelector {
    selector: CssSelector,
    binding: CssSelectorBinding,
}

impl CssNormalizedSelector {
    /// Borrows the authored selector, including repeated and function-contained anchors.
    #[must_use]
    pub const fn selector(&self) -> &CssSelector {
        &self.selector
    }

    /// Returns its binding without substituting or multiplying parent selectors.
    #[must_use]
    pub const fn binding(&self) -> CssSelectorBinding {
        self.binding
    }
}

/// A shared immutable selector list and its earlier parent/scope references.
///
/// Clones share one context. Distinct authored style rules have distinct
/// contexts even when their selectors are structurally equal. Nested declaration
/// runs reuse the exact enclosing context, including its per-selector specificity
/// and pseudo-elements; they do not synthesize an `&` rule. This identity is not
/// a mutable CSSOM object, revision, stable handle, or cross-normalization key.
#[derive(Clone, Debug)]
pub struct CssSelectorContext {
    context: Arc<SelectorContextData>,
}

#[derive(Debug)]
struct SelectorContextData {
    selectors: Vec<CssNormalizedSelector>,
    parent: Option<CssSelectorContext>,
    scope: Option<CssRuleContext>,
}

impl CssSelectorContext {
    /// Returns the complete authored list, with no selector Cartesian product.
    #[must_use]
    pub fn selectors(&self) -> &[CssNormalizedSelector] {
        &self.context.selectors
    }

    /// Returns the parent style list for nesting; scoped style roots have no such parent.
    #[must_use]
    pub fn parent(&self) -> Option<&Self> {
        self.context.parent.as_ref()
    }

    /// Returns the nearest enclosing authored scope rule, when present.
    #[must_use]
    pub fn scope_context(&self) -> Option<&CssRuleContext> {
        self.context.scope.as_ref()
    }

    /// Reports whether both handles refer to the same immutable context occurrence.
    #[must_use]
    pub fn same_context(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.context, &other.context)
    }

    fn ordinary(selectors: &CssStyleSelectorList, context: TraversalContext<'_>) -> Self {
        let selectors = selectors
            .selectors()
            .iter()
            .map(|entry| match entry {
                CssStyleSelector::Selector(selector) => {
                    let binding = if selector_has_anchor(selector, AnchorKind::Nesting) {
                        CssSelectorBinding::ExplicitAnchors
                    } else if context.selectors.is_some() {
                        CssSelectorBinding::ImplicitDescendant
                    } else {
                        CssSelectorBinding::Absolute
                    };
                    CssNormalizedSelector {
                        selector: selector.clone(),
                        binding,
                    }
                }
                CssStyleSelector::Relative(relative) => CssNormalizedSelector {
                    selector: relative.selector().clone(),
                    binding: CssSelectorBinding::LeadingCombinator(relative.combinator()),
                },
            })
            .collect();
        Self {
            context: Arc::new(SelectorContextData {
                selectors,
                parent: context.selectors.cloned(),
                scope: context.scope.cloned(),
            }),
        }
    }

    fn scoped(selectors: &CssScopedStyleSelectorList, context: TraversalContext<'_>) -> Self {
        let selectors = selectors
            .selectors()
            .iter()
            .map(|entry| match entry {
                CssScopedStyleSelector::Selector(selector) => CssNormalizedSelector {
                    selector: selector.clone(),
                    binding: if selector_has_anchor(selector, AnchorKind::Scope) {
                        CssSelectorBinding::ScopeAnchors
                    } else {
                        CssSelectorBinding::Absolute
                    },
                },
                CssScopedStyleSelector::Relative(relative) => CssNormalizedSelector {
                    selector: relative.selector().clone(),
                    binding: CssSelectorBinding::LeadingCombinator(relative.combinator()),
                },
            })
            .collect();
        Self {
            context: Arc::new(SelectorContextData {
                selectors,
                parent: None,
                scope: context.scope.cloned(),
            }),
        }
    }
}

/// A borrowed rule header or intact nonstyle payload in the normalized stream.
///
/// Group headers do not contain child subtrees. Even empty style rules expose
/// their complete shared selector context. Terminal payloads preserve their
/// typed authored contents without applying element-style declaration expansion.
#[non_exhaustive]
#[derive(Clone, Copy, Debug)]
pub enum CssRuleContextKindRef<'a> {
    Style(&'a CssSelectorContext),
    ScopedStyle(&'a CssSelectorContext),
    NestedDeclarations(&'a CssSelectorContext),
    Media(&'a CssMediaQueryList),
    Supports(&'a CssSupportsCondition),
    Container {
        name: Option<&'a CssContainerName>,
        condition: &'a CssContainerCondition,
    },
    LayerBlock(Option<&'a CssLayerName>),
    Scope {
        root: Option<&'a CssScopeSelectorList>,
        limit: Option<&'a CssScopeSelectorList>,
    },
    LayerStatement(&'a CssLayerNameList),
    Import(&'a CssImportRule),
    Namespace(&'a CssNamespaceRule),
    FontFace(&'a CssFontFaceRule),
    CustomMedia(&'a CssCustomMediaRule),
    FontFeatureValues(&'a CssFontFeatureValuesRule),
    Keyframes(&'a CssKeyframesRule),
    CounterStyle(&'a CssCounterStyleRule),
    Page(&'a CssPageRule),
}

#[derive(Debug)]
enum RuleContextKind {
    Style(CssSelectorContext),
    ScopedStyle(CssSelectorContext),
    NestedDeclarations(CssSelectorContext),
    Media(CssMediaQueryList),
    Supports(CssSupportsCondition),
    Container {
        name: Option<CssContainerName>,
        condition: CssContainerCondition,
    },
    LayerBlock(Option<CssLayerName>),
    Scope {
        root: Option<CssScopeSelectorList>,
        limit: Option<CssScopeSelectorList>,
    },
    LayerStatement(CssLayerNameList),
    Import(CssImportRule),
    Namespace(CssNamespaceRule),
    FontFace(CssFontFaceRule),
    CustomMedia(CssCustomMediaRule),
    FontFeatureValues(CssFontFeatureValuesRule),
    Keyframes(CssKeyframesRule),
    CounterStyle(CssCounterStyleRule),
    Page(CssPageRule),
}

/// One shared immutable authored rule occurrence and its enclosing rule reference.
///
/// Contexts contain only their header or terminal payload, never recursively
/// cloned group children. Parent and selector/scope links refer only to earlier
/// occurrences, preventing reference cycles. Equal anonymous layers and equal
/// style rules remain distinct occurrences. No mutable CSSOM identity is assigned.
#[derive(Clone, Debug)]
pub struct CssRuleContext {
    context: Arc<RuleContextData>,
}

#[derive(Debug)]
struct RuleContextData {
    kind: RuleContextKind,
    parent: Option<CssRuleContext>,
    position: Option<CssSourcePosition>,
}

impl CssRuleContext {
    /// Borrows the header or complete terminal payload.
    #[must_use]
    pub fn kind(&self) -> CssRuleContextKindRef<'_> {
        match &self.context.kind {
            RuleContextKind::Style(value) => CssRuleContextKindRef::Style(value),
            RuleContextKind::ScopedStyle(value) => CssRuleContextKindRef::ScopedStyle(value),
            RuleContextKind::NestedDeclarations(value) => {
                CssRuleContextKindRef::NestedDeclarations(value)
            }
            RuleContextKind::Media(value) => CssRuleContextKindRef::Media(value),
            RuleContextKind::Supports(value) => CssRuleContextKindRef::Supports(value),
            RuleContextKind::Container { name, condition } => CssRuleContextKindRef::Container {
                name: name.as_ref(),
                condition,
            },
            RuleContextKind::LayerBlock(value) => CssRuleContextKindRef::LayerBlock(value.as_ref()),
            RuleContextKind::Scope { root, limit } => CssRuleContextKindRef::Scope {
                root: root.as_ref(),
                limit: limit.as_ref(),
            },
            RuleContextKind::LayerStatement(value) => CssRuleContextKindRef::LayerStatement(value),
            RuleContextKind::Import(value) => CssRuleContextKindRef::Import(value),
            RuleContextKind::Namespace(value) => CssRuleContextKindRef::Namespace(value),
            RuleContextKind::CustomMedia(value) => CssRuleContextKindRef::CustomMedia(value),
            RuleContextKind::FontFeatureValues(value) => {
                CssRuleContextKindRef::FontFeatureValues(value)
            }
            RuleContextKind::FontFace(value) => CssRuleContextKindRef::FontFace(value),
            RuleContextKind::Keyframes(value) => CssRuleContextKindRef::Keyframes(value),
            RuleContextKind::CounterStyle(value) => CssRuleContextKindRef::CounterStyle(value),
            RuleContextKind::Page(value) => CssRuleContextKindRef::Page(value),
        }
    }

    /// Returns the immediate enclosing authored rule, including conditional groups.
    #[must_use]
    pub fn parent(&self) -> Option<&Self> {
        self.context.parent.as_ref()
    }

    /// Returns authored provenance when present; this is not a precedence key.
    #[must_use]
    pub fn position(&self) -> Option<CssSourcePosition> {
        self.context.position
    }

    /// Reports identity of this immutable normalization occurrence, not structural equality.
    #[must_use]
    pub fn same_context(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.context, &other.context)
    }
}

/// One emitted declaration occurrence, preserving grouped intrinsic expansion.
#[derive(Clone, Debug)]
pub struct CssNormalizedDeclaration {
    source: CssDeclaration,
    expansion: CssExpansion,
    selectors: CssSelectorContext,
    rule: CssRuleContext,
    order: usize,
}

impl CssNormalizedDeclaration {
    /// Returns the original immutable authored declaration occurrence.
    #[must_use]
    pub const fn source(&self) -> &CssDeclaration {
        &self.source
    }

    /// Returns intrinsic contributions or the unchanged symbolic pending handle.
    #[must_use]
    pub const fn expansion(&self) -> &CssExpansion {
        &self.expansion
    }

    /// Returns the complete shared selector context, without applying matching.
    #[must_use]
    pub const fn selector_context(&self) -> &CssSelectorContext {
        &self.selectors
    }

    /// Returns the immediate style or nested-declaration rule occurrence.
    #[must_use]
    pub const fn rule_context(&self) -> &CssRuleContext {
        &self.rule
    }

    /// Returns zero-based emitted declaration order, independent of source coordinates.
    /// Shorthand members share this ordinal; no cascade winner is selected.
    #[must_use]
    pub const fn order(&self) -> usize {
        self.order
    }
}

/// A rule occurrence or grouped declaration occurrence in authored depth-first order.
#[non_exhaustive]
#[derive(Clone, Debug)]
pub enum CssNormalizedItem {
    Rule(CssRuleContext),
    Declaration(CssNormalizedDeclaration),
}

/// An immutable stylesheet normalization containing every retained rule occurrence.
///
/// Each rule precedes its leading declarations and ordered children. Empty
/// groups, layer statements, imports, and nonstyle payloads remain observable.
/// Conditions, imports, scopes, layers, and symbolic values remain unevaluated.
/// Construction is owner-controlled and succeeds only for the implemented
/// intrinsic declaration-expansion coverage; this is not a claim of full CSS
/// grammar or expansion support.
#[derive(Clone, Debug)]
pub struct CssNormalizedSheet {
    encoding: Option<CssEncodingDeclaration>,
    items: Vec<CssNormalizedItem>,
}

impl CssNormalizedSheet {
    /// Returns preserved optional encoding metadata without decoding input bytes.
    #[must_use]
    pub const fn encoding(&self) -> Option<&CssEncodingDeclaration> {
        self.encoding.as_ref()
    }

    /// Returns the ordered rule/declaration stream, including empty rule occurrences.
    #[must_use]
    pub fn items(&self) -> &[CssNormalizedItem] {
        &self.items
    }
}

/// Normalized retained syntax alongside unchanged ordered parser diagnostics.
///
/// Normalization does not imply a clean parse. This separate report preserves
/// the original diagnostic order, spans, and recovery actions without running
/// parsing or selecting another grammar.
#[derive(Clone, Debug)]
pub struct CssNormalizedReport {
    syntax: CssNormalizedSheet,
    diagnostics: Vec<CssRecoveryDiagnostic>,
}

impl CssNormalizedReport {
    /// Borrows the successfully normalized retained syntax.
    #[must_use]
    pub const fn syntax(&self) -> &CssNormalizedSheet {
        &self.syntax
    }

    /// Returns the original parser diagnostics in their original order.
    #[must_use]
    pub fn diagnostics(&self) -> &[CssRecoveryDiagnostic] {
        &self.diagnostics
    }

    /// Reports exactly whether the original diagnostic slice was empty.
    #[must_use]
    pub fn is_clean(&self) -> bool {
        self.diagnostics.is_empty()
    }

    /// Transfers both outputs without discarding diagnostic provenance.
    #[must_use]
    pub fn into_parts(self) -> (CssNormalizedSheet, Vec<CssRecoveryDiagnostic>) {
        (self.syntax, self.diagnostics)
    }
}

/// Normalizes retained authored syntax atomically with default resource budgets.
///
/// Only emitted style declarations require intrinsic expansion. Unsupported
/// known declarations return a typed error, even when their authored grammar is
/// supported. Custom values, `all`, pending substitution, conditional headers,
/// and terminal payloads stay symbolic. The source sheet remains unchanged.
/// Keep the original parse report when its diagnostics matter, or use
/// [`normalize_report`]. Whole-sheet checked Rust construction is separate.
pub fn normalize_sheet(sheet: &CssSheet) -> Result<CssNormalizedSheet, CssNormalizationError> {
    normalize_sheet_with_limits(sheet, CssNormalizationLimits::default())
}

/// Normalizes under explicit traversal/output budgets, publishing no partial result.
///
/// Rule/declaration admission and contribution-member counts are checked before
/// allocating the corresponding header, expansion, or output item. Rule depth
/// is checked before rule count; declaration count precedes expansion capability
/// and member-budget checks. Terminal payload bytes have no separate budget.
pub fn normalize_sheet_with_limits(
    sheet: &CssSheet,
    limits: CssNormalizationLimits,
) -> Result<CssNormalizedSheet, CssNormalizationError> {
    let mut builder = Normalizer {
        limits,
        items: Vec::new(),
        rules: 0,
        declarations: 0,
        contributions: 0,
    };
    builder.ordinary_rules(sheet.rules(), TraversalContext::default(), 0)?;
    Ok(CssNormalizedSheet {
        encoding: sheet.encoding().cloned(),
        items: builder.items,
    })
}

/// Normalizes a parse report while preserving all recovery diagnostics unchanged.
pub fn normalize_report(
    report: &CssParseReport<CssSheet>,
) -> Result<CssNormalizedReport, CssNormalizationError> {
    normalize_report_with_limits(report, CssNormalizationLimits::default())
}

/// Preserves parser diagnostics while normalizing with explicit resource budgets.
pub fn normalize_report_with_limits(
    report: &CssParseReport<CssSheet>,
    limits: CssNormalizationLimits,
) -> Result<CssNormalizedReport, CssNormalizationError> {
    let syntax = normalize_sheet_with_limits(report.syntax(), limits)?;
    Ok(CssNormalizedReport {
        syntax,
        diagnostics: report.diagnostics().to_vec(),
    })
}

#[derive(Clone, Copy, Default)]
struct TraversalContext<'a> {
    rule: Option<&'a CssRuleContext>,
    selectors: Option<&'a CssSelectorContext>,
    scope: Option<&'a CssRuleContext>,
}

struct Normalizer {
    limits: CssNormalizationLimits,
    items: Vec<CssNormalizedItem>,
    rules: usize,
    declarations: usize,
    contributions: usize,
}

impl Normalizer {
    fn admit_rule(
        &mut self,
        position: Option<CssSourcePosition>,
        context: TraversalContext<'_>,
        depth: u32,
    ) -> Result<(), CssNormalizationError> {
        let failed = if depth > self.limits.max_rule_depth {
            Some((
                CssNormalizationResource::RuleDepth,
                self.limits.max_rule_depth as usize,
            ))
        } else if self.rules >= self.limits.max_rules {
            Some((CssNormalizationResource::Rules, self.limits.max_rules))
        } else {
            None
        };
        if let Some((resource, limit)) = failed {
            return Err(CssNormalizationError::new(
                CssNormalizationErrorKind::LimitExceeded { resource, limit },
                position,
                context.rule,
                None,
            ));
        }
        self.rules += 1;
        Ok(())
    }

    fn record_rule(
        &mut self,
        kind: RuleContextKind,
        position: Option<CssSourcePosition>,
        parent: Option<&CssRuleContext>,
    ) -> CssRuleContext {
        let rule = CssRuleContext {
            context: Arc::new(RuleContextData {
                kind,
                parent: parent.cloned(),
                position,
            }),
        };
        self.items.push(CssNormalizedItem::Rule(rule.clone()));
        rule
    }

    fn declarations(
        &mut self,
        declarations: &CssDeclarationList,
        rule: &CssRuleContext,
        selectors: &CssSelectorContext,
    ) -> Result<(), CssNormalizationError> {
        for source in declarations.iter() {
            let fail = |kind| {
                CssNormalizationError::new(
                    kind,
                    source.position(),
                    Some(rule),
                    Some((source, self.declarations)),
                )
            };
            if self.declarations >= self.limits.max_declarations {
                return Err(fail(CssNormalizationErrorKind::LimitExceeded {
                    resource: CssNormalizationResource::Declarations,
                    limit: self.limits.max_declarations,
                }));
            }
            let members = crate::expansion::expansion_member_count(source)
                .map_err(|error| fail(CssNormalizationErrorKind::UnsupportedDeclaration(error)))?;
            if members > self.limits.max_contributions - self.contributions {
                return Err(fail(CssNormalizationErrorKind::LimitExceeded {
                    resource: CssNormalizationResource::Contributions,
                    limit: self.limits.max_contributions,
                }));
            }
            let expansion = expand_declaration(source)
                .map_err(|error| fail(CssNormalizationErrorKind::UnsupportedDeclaration(error)))?;
            self.items
                .push(CssNormalizedItem::Declaration(CssNormalizedDeclaration {
                    source: source.clone(),
                    expansion,
                    selectors: selectors.clone(),
                    rule: rule.clone(),
                    order: self.declarations,
                }));
            self.declarations += 1;
            self.contributions += members;
        }
        Ok(())
    }

    fn ordinary_rules(
        &mut self,
        rules: &[CssRule],
        context: TraversalContext<'_>,
        depth: u32,
    ) -> Result<(), CssNormalizationError> {
        for rule in rules {
            let position = ordinary_position(rule);
            self.admit_rule(position, context, depth)?;
            match rule {
                CssRule::Style(style) => {
                    let selectors = CssSelectorContext::ordinary(style.selectors(), context);
                    let rule = self.record_rule(
                        RuleContextKind::Style(selectors.clone()),
                        position,
                        context.rule,
                    );
                    self.declarations(style.declarations(), &rule, &selectors)?;
                    self.ordinary_rules(
                        style.rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            selectors: Some(&selectors),
                            scope: context.scope,
                        },
                        depth + 1,
                    )?;
                }
                CssRule::NestedDeclarations(run) => {
                    let selectors = context.selectors.expect(
                        "the authored parser only creates declaration runs inside a style context",
                    );
                    let rule = self.record_rule(
                        RuleContextKind::NestedDeclarations(selectors.clone()),
                        position,
                        context.rule,
                    );
                    self.declarations(run.declarations(), &rule, selectors)?;
                }
                CssRule::Media(media) => {
                    let rule = self.record_rule(
                        RuleContextKind::Media(media.query().clone()),
                        position,
                        context.rule,
                    );
                    self.ordinary_rules(
                        media.rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            ..context
                        },
                        depth + 1,
                    )?;
                }
                CssRule::Supports(supports) => {
                    let rule = self.record_rule(
                        RuleContextKind::Supports(supports.condition().clone()),
                        position,
                        context.rule,
                    );
                    self.ordinary_rules(
                        supports.rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            ..context
                        },
                        depth + 1,
                    )?;
                }
                CssRule::Container(container) => {
                    let rule = self.record_rule(
                        RuleContextKind::Container {
                            name: container.name().cloned(),
                            condition: container.condition().clone(),
                        },
                        position,
                        context.rule,
                    );
                    self.ordinary_rules(
                        container.rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            ..context
                        },
                        depth + 1,
                    )?;
                }
                CssRule::LayerBlock(layer) => {
                    let rule = self.record_rule(
                        RuleContextKind::LayerBlock(layer.name().cloned()),
                        position,
                        context.rule,
                    );
                    self.ordinary_rules(
                        layer.rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            ..context
                        },
                        depth + 1,
                    )?;
                }
                CssRule::Scope(scope) => self.scope(scope, context, position, depth)?,
                CssRule::Import(value) => {
                    self.record_rule(
                        RuleContextKind::Import(value.clone()),
                        position,
                        context.rule,
                    );
                }
                CssRule::Namespace(value) => {
                    self.record_rule(
                        RuleContextKind::Namespace(value.clone()),
                        position,
                        context.rule,
                    );
                }
                CssRule::LayerStatement(value) => {
                    self.record_rule(
                        RuleContextKind::LayerStatement(value.names().clone()),
                        position,
                        context.rule,
                    );
                }
                CssRule::CustomMedia(value) => {
                    self.record_rule(
                        RuleContextKind::CustomMedia(value.clone()),
                        position,
                        context.rule,
                    );
                }
                CssRule::FontFeatureValues(value) => {
                    self.record_rule(
                        RuleContextKind::FontFeatureValues(value.clone()),
                        position,
                        context.rule,
                    );
                }
                CssRule::FontFace(value) => {
                    self.record_rule(
                        RuleContextKind::FontFace(value.clone()),
                        position,
                        context.rule,
                    );
                }
                CssRule::Keyframes(value) => {
                    self.record_rule(
                        RuleContextKind::Keyframes(value.clone()),
                        position,
                        context.rule,
                    );
                }
                CssRule::CounterStyle(value) => {
                    self.record_rule(
                        RuleContextKind::CounterStyle(value.clone()),
                        position,
                        context.rule,
                    );
                }
                CssRule::Page(value) => {
                    self.record_rule(RuleContextKind::Page(value.clone()), position, context.rule);
                }
            }
        }
        Ok(())
    }

    fn scope(
        &mut self,
        scope: &CssScopeRule,
        context: TraversalContext<'_>,
        position: Option<CssSourcePosition>,
        depth: u32,
    ) -> Result<(), CssNormalizationError> {
        let rule = self.record_rule(
            RuleContextKind::Scope {
                root: scope.root().cloned(),
                limit: scope.limit().cloned(),
            },
            position,
            context.rule,
        );
        self.scoped_rules(
            scope.rules().rules(),
            TraversalContext {
                rule: Some(&rule),
                selectors: None,
                scope: Some(&rule),
            },
            depth + 1,
        )
    }

    fn scoped_rules(
        &mut self,
        rules: &[CssScopedRule],
        context: TraversalContext<'_>,
        depth: u32,
    ) -> Result<(), CssNormalizationError> {
        for rule in rules {
            let position = scoped_position(rule);
            self.admit_rule(position, context, depth)?;
            match rule {
                CssScopedRule::Style(style) => {
                    let selectors = CssSelectorContext::scoped(style.selectors(), context);
                    let rule = self.record_rule(
                        RuleContextKind::ScopedStyle(selectors.clone()),
                        position,
                        context.rule,
                    );
                    self.declarations(style.declarations(), &rule, &selectors)?;
                    self.ordinary_rules(
                        style.rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            selectors: Some(&selectors),
                            scope: context.scope,
                        },
                        depth + 1,
                    )?;
                }
                CssScopedRule::Media(media) => {
                    let rule = self.record_rule(
                        RuleContextKind::Media(media.query().clone()),
                        position,
                        context.rule,
                    );
                    self.scoped_rules(
                        media.rules().rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            ..context
                        },
                        depth + 1,
                    )?;
                }
                CssScopedRule::Supports(supports) => {
                    let rule = self.record_rule(
                        RuleContextKind::Supports(supports.condition().clone()),
                        position,
                        context.rule,
                    );
                    self.scoped_rules(
                        supports.rules().rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            ..context
                        },
                        depth + 1,
                    )?;
                }
                CssScopedRule::Container(container) => {
                    let rule = self.record_rule(
                        RuleContextKind::Container {
                            name: container.name().cloned(),
                            condition: container.condition().clone(),
                        },
                        position,
                        context.rule,
                    );
                    self.scoped_rules(
                        container.rules().rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            ..context
                        },
                        depth + 1,
                    )?;
                }
                CssScopedRule::LayerBlock(layer) => {
                    let rule = self.record_rule(
                        RuleContextKind::LayerBlock(layer.name().cloned()),
                        position,
                        context.rule,
                    );
                    self.scoped_rules(
                        layer.rules().rules(),
                        TraversalContext {
                            rule: Some(&rule),
                            ..context
                        },
                        depth + 1,
                    )?;
                }
                CssScopedRule::LayerStatement(value) => {
                    self.record_rule(
                        RuleContextKind::LayerStatement(value.names().clone()),
                        position,
                        context.rule,
                    );
                }
                CssScopedRule::CustomMedia(value) => {
                    self.record_rule(
                        RuleContextKind::CustomMedia(value.clone()),
                        position,
                        context.rule,
                    );
                }
                CssScopedRule::FontFeatureValues(value) => {
                    self.record_rule(
                        RuleContextKind::FontFeatureValues(value.clone()),
                        position,
                        context.rule,
                    );
                }
                CssScopedRule::Scope(scope) => self.scope(scope, context, position, depth)?,
            }
        }
        Ok(())
    }
}

fn ordinary_position(rule: &CssRule) -> Option<CssSourcePosition> {
    Some(match rule {
        CssRule::Style(value) => value.position(),
        CssRule::NestedDeclarations(value) => {
            return value
                .declarations()
                .first()
                .and_then(CssDeclaration::position);
        }
        CssRule::Import(value) => return value.position(),
        CssRule::Namespace(value) => value.position(),
        CssRule::CounterStyle(value) => value.position(),
        CssRule::Page(value) => value.position(),
        CssRule::LayerStatement(value) => value.position(),
        CssRule::LayerBlock(value) => value.position(),
        CssRule::CustomMedia(value) => return value.position(),
        CssRule::FontFeatureValues(value) => return value.position(),
        CssRule::FontFace(value) => value.position(),
        CssRule::Keyframes(value) => value.position(),
        CssRule::Media(value) => value.position(),
        CssRule::Supports(value) => value.position(),
        CssRule::Container(value) => value.position(),
        CssRule::Scope(value) => value.position(),
    })
}

fn scoped_position(rule: &CssScopedRule) -> Option<CssSourcePosition> {
    Some(match rule {
        CssScopedRule::CustomMedia(value) => return value.position(),
        CssScopedRule::FontFeatureValues(value) => return value.position(),
        CssScopedRule::Style(value) => value.position(),
        CssScopedRule::Media(value) => value.position(),
        CssScopedRule::Supports(value) => value.position(),
        CssScopedRule::Container(value) => value.position(),
        CssScopedRule::LayerStatement(value) => value.position(),
        CssScopedRule::LayerBlock(value) => value.position(),
        CssScopedRule::Scope(value) => value.position(),
    })
}

#[derive(Clone, Copy)]
enum AnchorKind {
    Nesting,
    Scope,
}

fn selector_has_anchor(selector: &CssSelector, kind: AnchorKind) -> bool {
    match selector {
        CssSelector::Compound(compound) => compound_has_anchor(compound, kind),
        CssSelector::Complex(complex) => {
            compound_has_anchor(complex.first(), kind)
                || complex
                    .rest()
                    .iter()
                    .any(|part| compound_has_anchor(part.selector(), kind))
        }
        CssSelector::PseudoClass(pseudo) => pseudo_has_anchor(pseudo, kind),
        CssSelector::Tag(_) | CssSelector::Key(_) | CssSelector::Class(_) => false,
    }
}

fn compound_has_anchor(compound: &CssCompoundSelector, kind: AnchorKind) -> bool {
    let direct = match kind {
        AnchorKind::Nesting => compound.nesting_selectors() > 0,
        AnchorKind::Scope => compound.has_scope_anchor(),
    };
    direct
        || compound
            .pseudo_classes()
            .iter()
            .any(|pseudo| pseudo_has_anchor(pseudo, kind))
}

fn pseudo_has_anchor(pseudo: &CssPseudoClass, kind: AnchorKind) -> bool {
    match pseudo {
        CssPseudoClass::Not(list) | CssPseudoClass::Is(list) | CssPseudoClass::Where(list) => list
            .selectors()
            .iter()
            .any(|selector| selector_has_anchor(selector, kind)),
        CssPseudoClass::Has(list) => list
            .selectors()
            .iter()
            .any(|relative| selector_has_anchor(relative.selector(), kind)),
        CssPseudoClass::NthChild(pattern) | CssPseudoClass::NthLastChild(pattern) => {
            pattern.selector_list().is_some_and(|list| {
                list.selectors()
                    .iter()
                    .any(|selector| selector_has_anchor(selector, kind))
            })
        }
        CssPseudoClass::Root
        | CssPseudoClass::Scope
        | CssPseudoClass::Link
        | CssPseudoClass::Visited
        | CssPseudoClass::Target
        | CssPseudoClass::Dir(_)
        | CssPseudoClass::Lang(_)
        | CssPseudoClass::Hover
        | CssPseudoClass::Active
        | CssPseudoClass::Focus
        | CssPseudoClass::FocusVisible
        | CssPseudoClass::FocusWithin
        | CssPseudoClass::Disabled
        | CssPseudoClass::Enabled
        | CssPseudoClass::Checked
        | CssPseudoClass::Required
        | CssPseudoClass::Optional
        | CssPseudoClass::Valid
        | CssPseudoClass::Invalid
        | CssPseudoClass::PlaceholderShown
        | CssPseudoClass::FirstChild
        | CssPseudoClass::LastChild
        | CssPseudoClass::OnlyChild
        | CssPseudoClass::Empty
        | CssPseudoClass::FirstOfType
        | CssPseudoClass::LastOfType
        | CssPseudoClass::OnlyOfType
        | CssPseudoClass::NthOfType(_)
        | CssPseudoClass::NthLastOfType(_)
        | CssPseudoClass::Modal
        | CssPseudoClass::Fullscreen
        | CssPseudoClass::PopoverOpen
        | CssPseudoClass::Default
        | CssPseudoClass::Indeterminate
        | CssPseudoClass::ReadOnly
        | CssPseudoClass::ReadWrite
        | CssPseudoClass::InRange
        | CssPseudoClass::OutOfRange => false,
    }
}

#[cfg(test)]
mod import_construction_tests {
    use super::*;
    use crate::{
        CssComponentValue, CssComponentValues, CssNamespaceContext, CssValueOrigin,
        parse_component_values,
    };

    #[test]
    fn programmatic_and_parsed_import_origins_survive_normalization() {
        let parsed_keyword = parse_component_values("/*😀*/@import")
            .unwrap()
            .items()
            .last()
            .unwrap()
            .clone();
        let original_origin = parsed_keyword.origin().clone();
        let mut sheet = CssSheet::new();
        for (keyword, target) in [
            (CssComponentValue::try_token("@import").unwrap(), "'a'"),
            (parsed_keyword, "'b'"),
        ] {
            let components = CssComponentValues::try_new(vec![
                keyword,
                CssComponentValue::try_token(" ").unwrap(),
                CssComponentValue::try_token(target).unwrap(),
                CssComponentValue::try_token(";").unwrap(),
            ])
            .unwrap();
            sheet.push_rule(CssRule::Import(
                CssImportRule::try_from_components(components, &CssNamespaceContext::default())
                    .unwrap(),
            ));
        }
        let normalized = normalize_sheet(&sheet).unwrap();
        drop(sheet);
        let [
            CssNormalizedItem::Rule(first),
            CssNormalizedItem::Rule(second),
        ] = normalized.items()
        else {
            panic!("two intact import occurrences in authored order")
        };
        assert_eq!(first.position(), None);
        let CssRuleContextKindRef::Import(first_import) = first.kind() else {
            panic!("programmatic import")
        };
        assert_eq!(first_import.origin(), &CssValueOrigin::Programmatic);
        assert_eq!(first_import.serialize().unwrap().as_css(), "@import 'a';");
        let CssRuleContextKindRef::Import(second_import) = second.kind() else {
            panic!("import with original parsed at-keyword")
        };
        let (CssValueOrigin::Parsed(actual), CssValueOrigin::Parsed(expected)) =
            (second_import.origin(), &original_origin)
        else {
            panic!("original parsed keyword provenance")
        };
        assert!(actual.source().same_snapshot(expected.source()));
        assert_eq!(actual.span(), expected.span());
        assert_eq!(second.position(), Some(expected.span().start()));
        assert_eq!(second_import.serialize().unwrap().as_css(), "@import 'b';");
        assert!(first.parent().is_none());
        assert!(second.parent().is_none());
    }
}
